global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using AventStack.ExtentReports;
global using AventStack.ExtentReports.Reporter;
global using System.Reflection;
global using RestSharp;
global using static System.Runtime.InteropServices.JavaScript.JSType;